-- Supabase schema reference (context only; not for execution)
-- Provided by user. Do not run as-is.

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action character varying NOT NULL,
  resource_type character varying NOT NULL,
  resource_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  session_id character varying,
  timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.case_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  precedent_id uuid NOT NULL,
  judge_id uuid,
  case_duration_days integer,
  case_complexity_score numeric,
  decision_type character varying,
  appeal_outcome character varying,
  legal_principles ARRAY,
  cited_precedents ARRAY,
  statistical_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT case_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT case_analytics_precedent_id_fkey FOREIGN KEY (precedent_id) REFERENCES public.precedents_metadata(id),
  CONSTRAINT case_analytics_judge_id_fkey FOREIGN KEY (judge_id) REFERENCES public.judges(id)
);
CREATE TABLE public.citations_metadata (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  local_citation_id uuid NOT NULL,
  document_id uuid NOT NULL,
  citation_text_preview character varying,
  citation_type character varying NOT NULL,
  case_name character varying,
  court character varying,
  year integer,
  volume character varying,
  reporter character varying,
  page character varying,
  jurisdiction character varying,
  is_validated boolean DEFAULT false,
  validation_status character varying DEFAULT 'pending'::character varying,
  confidence_score numeric,
  created_at timestamp with time zone DEFAULT now(),
  validated_at timestamp with time zone,
  CONSTRAINT citations_metadata_pkey PRIMARY KEY (id),
  CONSTRAINT citations_metadata_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents_metadata(id)
);
CREATE TABLE public.collaborations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  collaborator_id uuid NOT NULL,
  permission_level character varying NOT NULL,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  status character varying DEFAULT 'pending'::character varying,
  invitation_token character varying,
  expires_at timestamp with time zone,
  CONSTRAINT collaborations_pkey PRIMARY KEY (id),
  CONSTRAINT collaborations_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents_metadata(id),
  CONSTRAINT collaborations_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id),
  CONSTRAINT collaborations_collaborator_id_fkey FOREIGN KEY (collaborator_id) REFERENCES public.users(id)
);
CREATE TABLE public.document_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  user_id uuid NOT NULL,
  content text NOT NULL,
  position_start integer,
  position_end integer,
  page_number integer,
  thread_id uuid,
  is_resolved boolean DEFAULT false,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_comments_pkey PRIMARY KEY (id),
  CONSTRAINT document_comments_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents_metadata(id),
  CONSTRAINT document_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT document_comments_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.document_comments(id),
  CONSTRAINT document_comments_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id)
);
CREATE TABLE public.document_edits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  user_id uuid NOT NULL,
  edit_type character varying NOT NULL,
  position_start integer,
  position_end integer,
  old_content_hash character varying,
  new_content_hash character varying,
  timestamp timestamp with time zone DEFAULT now(),
  session_id character varying,
  CONSTRAINT document_edits_pkey PRIMARY KEY (id),
  CONSTRAINT document_edits_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents_metadata(id),
  CONSTRAINT document_edits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.document_folders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid,
  name character varying NOT NULL,
  description text,
  parent_folder_id uuid,
  path text,
  is_shared boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_folders_pkey PRIMARY KEY (id),
  CONSTRAINT document_folders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT document_folders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT document_folders_parent_folder_id_fkey FOREIGN KEY (parent_folder_id) REFERENCES public.document_folders(id)
);
CREATE TABLE public.document_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  version_number integer NOT NULL,
  file_path text NOT NULL,
  file_hash character varying NOT NULL,
  changes_summary text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_versions_pkey PRIMARY KEY (id),
  CONSTRAINT document_versions_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents_metadata(id),
  CONSTRAINT document_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.documents_metadata (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  local_document_id uuid NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid,
  title character varying NOT NULL,
  description text,
  document_type character varying NOT NULL,
  language character varying DEFAULT 'english'::character varying,
  file_name character varying NOT NULL,
  file_size bigint NOT NULL,
  mime_type character varying NOT NULL,
  file_hash character varying NOT NULL,
  storage_provider character varying DEFAULT 'local'::character varying,
  is_processed boolean DEFAULT false,
  processing_status character varying DEFAULT 'pending'::character varying,
  is_public boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  folder_id uuid,
  tags ARRAY,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  version_number integer DEFAULT 1,
  CONSTRAINT documents_metadata_pkey PRIMARY KEY (id),
  CONSTRAINT documents_metadata_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT documents_metadata_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT documents_metadata_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.document_folders(id)
);
CREATE TABLE public.judges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  title character varying,
  court character varying,
  jurisdiction character varying,
  appointment_date date,
  retirement_date date,
  specializations ARRAY,
  bio text,
  photo_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT judges_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  type character varying NOT NULL,
  address text,
  phone character varying,
  email character varying,
  website character varying,
  license_number character varying,
  is_active boolean DEFAULT true,
  subscription_plan character varying DEFAULT 'basic'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.precedents_metadata (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  local_precedent_id uuid,
  case_name character varying NOT NULL,
  case_number character varying,
  court character varying NOT NULL,
  judge_names ARRAY,
  decision_date date,
  jurisdiction character varying,
  case_type character varying,
  legal_areas ARRAY,
  keywords ARRAY,
  summary text,
  citation character varying,
  parties_plaintiff ARRAY,
  parties_defendant ARRAY,
  outcome character varying,
  language character varying DEFAULT 'english'::character varying,
  source_database character varying,
  external_id character varying,
  is_landmark boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT precedents_metadata_pkey PRIMARY KEY (id)
);
CREATE TABLE public.search_queries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  query_text text NOT NULL,
  search_type character varying NOT NULL,
  filters jsonb,
  results_count integer,
  search_time_ms integer,
  clicked_results ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT search_queries_pkey PRIMARY KEY (id),
  CONSTRAINT search_queries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key character varying NOT NULL UNIQUE,
  value jsonb NOT NULL,
  description text,
  is_encrypted boolean DEFAULT false,
  last_modified_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id),
  CONSTRAINT system_settings_last_modified_by_fkey FOREIGN KEY (last_modified_by) REFERENCES public.users(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token_hash character varying NOT NULL UNIQUE,
  device_info jsonb,
  ip_address inet,
  user_agent text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_activity timestamp with time zone DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  username character varying,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  role character varying NOT NULL DEFAULT 'user'::character varying,
  organization_id uuid,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  profile_image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone,
  password_reset_token character varying,
  password_reset_expires timestamp with time zone,
  verification_token character varying,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
